### ISSUE TITLE
Crash in VCV Rack/host module

### ISSUE THREAD

**Issue by nay-seven** [madronalabs/aaltoverb-issues#1]
Hello,

to inform you that Aaltoverb crash directly here when loaded in vcv rack in the Host module

vcvrack pro 2.0.6
Mac Os Mojave

here the log:

[log.txt](https://github.com/madronalabs/aaltoverb-issues/files/8164373/log.txt)

**Comment by madronalabs** [comment]
Fixed this crash. Cause: View expecting a nonexistent Controller on shutdown.

**Comment by nay-seven** [comment]
hello, still directly crash vcv rack here when choosing aaltoverb in host module 
tested with host, host-fx, host-xl
tested on 2 machines
macbook pro 2015/Mojave vcvrack pro 2.0.6
Mac MIni 2012 Catalina vcvrack pro 2.0.6

here the log for the mac mini:
[crash mac mini.rtf.zip](https://github.com/madronalabs/aaltoverb-issues/files/8554278/crash.mac.mini.rtf.zip)

**Comment by madronalabs** [comment]
Sorry for the confusion. I wrote in error above—there were two crashes, the one on startup was in VCV Rack. They fixed that and it will come out with the next VCV Rack update.

**Comment by nay-seven** [comment]
ok, i understand !
