### ISSUE TITLE
Not recognized in Usine Hollyhock

### ISSUE THREAD

**Issue by nay-seven** [madronalabs/aaltoverb-issues#11]
previous version was working in Usine, but not the last one (2.0.0b3) ( invalid plugin):

<img width="539" alt="Capture d’écran 2022-04-14 à 16 26 06" src="https://user-images.githubusercontent.com/13808201/163411338-4792b141-cbdf-4872-a4b3-2c05c12af01e.png">

still crash in vcv rack/host module

vst3 works in Bespoke

**Comment by madronalabs** [comment]
Please note: An issue is meant to keep track of one problem, so I can fix it! When you add "+ still crashing vcv rack" that is not helpful. I already have an open issue about VCV Rack.

**Comment by madronalabs** [comment]
could not reproduce.
