### ISSUE TITLE
MIDI Learn in some daw's

### ISSUE THREAD

**Issue by nay-seven** [madronalabs/aaltoverb-issues#2]
Hello,

i successfully create MIDI learn in BespokeSynth (https://www.bespokesynth.com/) and in Reaper

But can't in the last stable version of Usine HH5 OSX64 5.1.211124 (http://brainmodular.com/usine.php#downloads)

**Comment by madronalabs** [comment]
Thanks for posting these as github issues with the supporting files! –Randy

**Comment by nay-seven** [comment]
Hello, 
sorry, but not sure to understand, what do you mean by "supporting files " ?
You need a patch for Usine HH5 to show you the issue?

**Comment by madronalabs** [comment]
No I mean the log file you already sent. Thanks for it! That was my point. Not that I need anything else.

**Comment by nay-seven** [comment]
ok, ok ! 
cool ;-)

**Comment by madronalabs** [comment]
There was a MIDI Learn issue with the Audio Units version (in all DAWs) that I just fixed. I am guessing that's what this was.
