### ISSUE TITLE
Parameter names blank in Audio Unit version

### ISSUE THREAD

**Issue by madronalabs** [madronalabs/aaltoverb-issues#8]
The oddity: In Reaper (6.50, on macOS11, but I’m guessing this’ll be the same everywhere), the parameter modulation/linking menu has all the parameters unnamed. Figured out that the first four are the ones I care about (the main controls), and the last one is the preset slider, and I’m guessing the rest are all the LFO controls. None the less I figure it’d be nice to have names in those lists.

**Comment by nay-seven** [comment]
i can confirm that in Usine Hollyhock, Mac Os Mojave
Here Aalto & Aaltoverb:
![aaltoverb parameters](https://user-images.githubusercontent.com/13808201/157187451-4d2d9011-9dde-44a1-8d52-072554b5065a.jpg)

**Comment by madronalabs** [comment]
This affects the Audio Unit version only!

**Comment by madronalabs** [comment]
fixed for 2.0.0b3.
